### ISSUE TITLE
"jadx" command in line 46 of "reverse-apk" file

### ISSUE THREAD

**Issue by Yogehi** [1N3/ReverseAPK#2]
line 46 tries to call "jadx". however, "jadx" does not come pre-installed with some distributions (such as kali) and installing "jadx" usually involves cloning the github repository "https://github.com/skylot/jadx". 

installing "jadx" is not present on the install script for "reverseAPK".

**Comment by 1N3** [comment]
Thanks for the heads up! I uploaded a fix to the install script which is now public that should download and install jadx.
