### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Darkcast** [1N3/ReverseAPK#3]
I am running kali linux lastest version I got an error while installing 

Linux kali 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux

[errormsg.txt](https://github.com/1N3/ReverseAPK/files/2064277/errormsg.txt)

**Comment by 1N3** [comment]
Looks like the Java version you're running is too low.

Execution failed for task ':jadx-gui:createExe'.
> net.sf.launch4j.BuilderException: Invalid data: Minimum JRE version should be x.x.x[_xx] 

I'd try upgrading Java and re-running the installer script again to see if that works.

**Comment by Darkcast** [comment]
Will check if the issue is fixed 
https://github.com/skylot/jadx/issues/291

**Comment by Darkcast** [comment]
The issue was fixed
Thanks
